config/routes.rb
GitSee::Application.routes.draw do
  root 'repos#show'
  get '/repo' => 'repos#show'
  get '/repo/:github_user/:github_repo' => 'repos#show'
  get '/gem/:name' => 'gemms#show'
  post '/resource/create'=> 'resources#create', as: "create_resource"
  post '/resource/:id:/vote' => 'resources#vote'

  #Routes for GitHub Oauth need refine and clean up
  get '/users/callback' => 'users#callback'
  get '/sessions/:id/create' => 'sessions#create', as: 'create_user_session'
  get '/sessions/:id/destroy' => 'sessions#destroy', as: 'destroy_user_session'
  get '/users/create' => 'users#create', as: 'create_user'
  get '/users/:id' => 'users#show', as: 'user'
  get '/select/:login' => 'welcome#select', as: 'select'
end

app/models/gemm.rb
class Gemm < ActiveRecord::Base
	has_many :resources 
	has_and_belongs_to_many :repos
end

app/models/repo.rb
class Repo < ActiveRecord::Base
		include HTTParty
			has_and_belongs_to_many :gemms

	# http://edgeguides.rubyonrails.org/active_record_callbacks.html
	before_validation :parse_and_store_gemms

	# Overloading the as_json method
	# to include gemms in the json object returned
	# as_json is automatically called when you return json
	def as_json(options={})
		super(options.merge(include: :gemms))
	end

	private # can only be called from within the model

	def parse_and_store_gemms
    gemm_list = mine_gems
		gemm_list.each do |gemm|
			self.gemms << Gemm.find_or_create_by(name: gemm)
		end
	end

  def mine_gems
    url = "http://raw.github.com/#{username}/#{name}/master/Gemfile"
    response = HTTParty.get(url)
    gemms = []
    begin
      response.each_line do |line|
        gemms << $1 if line =~ ( /gem\s\'(.*?)\'/ || /gem\s\"(.*?)\"/ )
      end
    rescue => err
      puts "Exception: #{err}"
    end
    return gemms
  end
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :gemm
	belongs_to :user
	has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :votes
	has_many :resources 
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gemms_controller.rb
class GemmsController < ApplicationController
	 respond_to :html, :json

	  def show
    match = Gemm.where(name: params[:name])
    @gemm = match.first
    respond_with @gemm
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

	def show
		@resource = Resource.new 
		@repo = Repo.find_or_create_by(username: params[:github_user], name: params[:github_repo])
		respond_to do |format|
			format.html { @repo }
			format.js 
		end 
	end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

	def create
		@resource = Resource.new(resource_params)
		# @resource.user = current_user
		if @resource.save
			respond_to do |format|
				format.js
			end
		else
			flash.now.alert = "Link Didn't Save. Check the link and try again!"
		end
	end 

	# add in method for up and downs of resources
	def vote
		@resource = Resource.find(params[:id])
		@vote = Vote.new(vote_params)
		@vote.user = current_user
		if @vote.save 
			respond_to do |format|
				format.js 
			end
		else 
			flash.now.alert = "Try again, and make sure your logged in to vote!"
		end
	end 

	private

	def resource_params
		params.require(:resource).permit(:site_name, :site_url, :gemm_id , :user_id)
	end

	def vote_params
		params.require(:vote).permit(:up, :down , :total_votes , :user_id , :resource_id)
	end 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gemms_helper.rb
module GemmsHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gemms/_gemm.html.erb
<div class="gem" id='gem-<%= gemm.id %>'>

	<div>		<h2>		Name: <%= gemm.name %> </h2></div>
			<div>				Downloads: <%=gemm.downloads %> </div>
			<div>				Updated_at: <%= gemm.updated_at %> </div>
			<div>				Downloads: <%= gemm.downloads %> </div>
			<div>				Version: <%= gemm.version %> </div>
			<div>				Project_url: <%= gemm.project_url %> </div>
			<div>				Real_name: <%= gemm.real_name %> </div>
				<div>			Version_downloads: <%= gemm.version_downloads %> </div>
				<div>			gemm_uri: <%= gemm.gem_uri %>  </div>
				<div>			Homepage_uri: <%= gemm.homepage_uri %> </div>
					<div>		Wiki_uri: <%= gemm.wiki_uri %> </div>
					<div>		Mailing_list_uri: <%= gemm.mailing_list_uri %> </div>
					<div>		Source_code_uri: <%= gemm.source_code_uri %> </div>
					<div>		Bug_tracker_uri: <%= gemm.bug_tracker_uri %>  </div>
		</div>

  <div class="gem-resources">
    <h3>Resources</h3>
    <%#= render partial: "resources/resource", collection: gemm.resources %>
  </div>
  <div class="resource-form">
    <%= form_for gemm.resources.build, url: create_resource_path, remote: true do |f| %>
    <%#= f.hidden_field :gemm_id, value: gemm.id %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.submit "New Link" %>
    <% end %>
  </div>
</div> 

app/views/gemms/show.html.erb
	Name: <%= @gemm.name %>
	Downloads: <%=@gemm.downloads %>
	Updated_at: <%= @gemm.updated_at %>
	Downloads: <%= @gemm.downloads %>
	Version: <%= @gemm.version %>
	Project_url: <%= @gemm.project_url %>
	Real_name: <%= @gemm.real_name %> 
	Version_downloads: <%= @gemm.version_downloads %>
	gemm_uri: <%= @gemm.gem_uri %> 
	Homepage_uri: <%= @gemm.homepage_uri %> 
	Wiki_uri: <%= @gemm.wiki_uri %>
	Mailing_list_uri: <%= @gemm.mailing_list_uri %>
	Source_code_uri: <%= @gemm.source_code_uri %>
	Bug_tracker_uri: <%= @gemm.bug_tracker_uri %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitSee</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/repos/show.html.erb
<div>
  <%= form_tag '/repo', remote: true, method: 'get' do %>
    <%= label_tag "github user" %>
    <%= text_field_tag :github_user %>
    <%= label_tag "github repo" %>
    <%= text_field_tag :github_repo %>
    <%= submit_tag "Search" %>
  <% end %> 
</div>

<h1 id="repo-title"><%= @repo.name %></h1>

<div class="gems">
  <h5>Gems</h5>
  <%= render partial: "gemms/gemm", collection: @repo.gemms %>
</div>

app/views/repos/show.js.erb
//Clear search box

GitSee.stateObj = { foo: "bar" };
// history.pushState(stateObj, title, url);
history.pushState(GitSee.stateObj, 
                  "<%= @repo.username %>" + ": " + "<%= @repo.name %>" + " " + "documentation", 
                  "/repo/" + "<%= @repo.username %>" + "/" + "<%= @repo.name %>");

$('#repo-title').html('<%= @repo.name %>');
$('.gems').val('');
$('.gems').html("<%= escape_javascript( render partial: "gemms/gemm", collection: @repo.gemms ) %>");

// Setup a click event on the gem, so when they are clicked, they show all gem-resources

// $('.gem-name').on('click', function(){
// 	$('.gem-resources').toggle();
// })

app/views/resources/create.js.erb
$(".gem-resources").append("<%= escape_javascript( render partial: "resources/resource", locals: {resource: @resource} ) %>");